# Generated by Django 3.2.6 on 2021-08-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Max_Hum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('hum_max', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Max_Pres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('pres_max', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Max_Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('temp_max', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Min_Hum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('hum_min', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Min_Pres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('pres_min', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Min_Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('temp_min', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Valeurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('temperature', models.FloatField()),
                ('humidite', models.FloatField()),
                ('pression', models.FloatField()),
                ('pnt_de_rosée', models.FloatField()),
                ('humidite_absolue', models.FloatField()),
                ('tension_de_vapeur', models.FloatField()),
                ('pression_cal', models.FloatField()),
            ],
        ),
    ]
